---
title: "R Notebook"
output: html_notebook
---

```{r}
library(magrittr)
library(dplyr)
library(ggpubr)
library(lmerTest)
```


```{r}
idR <- subset(orderDf, subID==52063)

library(tidyverse)
test<-orderDf %>% group_by(subID,id) %>%
  select(T.Sim, selfResp) %>%
  summarise(bet= cor(x=T.Sim,y=selfResp, use = "complete.obs", method="spearman")  ) %>%
  group_by(id) %>%
  summarise(betM=mean(bet, na.rm=T))

```

```{r}

library(MASS)
library(ggpubr)
mds <- cbind(cmdscale(dist(idR$selfResp), k=1),cmdscale(dist(idR$T.Sim), k=1))

traitsWide <- pivot_wider(orderDf, names_from = "subID", values_from = "selfResp", id_cols = c("traits","id"))

traitsWide2 <- traitsWide %>% group_by(traits) %>% dplyr::select(3:last_col()) %>% distinct()
selfDists<-traitsWide2[2:ncol(traitsWide2)] %>% dist() %>% as.matrix(.)


traitsWideID <- pivot_wider(orderDf, names_from = "subID", values_from = "T.Sim", id_cols = c("traits","id"))

for(ide in unique(traitsWide$id )){
  traitsWide2 <- traitsWideID %>% filter(id==ide) %>% group_by(traits) %>% dplyr::select(3:last_col()) %>% distinct()
  simDists<-traitsWide2[2:ncol(traitsWide2)] %>% dist() %>% as.matrix(.)
  assign(paste0(ide,"SimDists"),simDists)
  
  isoMDS(selfDists,k=2)
}


```

```{r}
    cur<-orderDf[, c("order","T.Sim")]
  
    PCAall<- prcomp(na.omit(cur),
             center = TRUE,
            scale. = TRUE)
    orderDf$PCAall[!is.na(orderDf$order) & !is.na(orderDf$T.Sim)] <- PCAall$x[,1]
for(i in unique(orderDf$subID)){
  
    cur<-orderDf[orderDf$subID==i, c("order","T.Sim")]
  
    PCAsub<- prcomp(na.omit(cur),
             center = TRUE,
            scale. = TRUE)
    orderDf$PCAsub[orderDf$subID==i & !is.na(orderDf$order) & !is.na(orderDf$T.Sim)] <- PCAsub$x[,1]
  
  for(j in unique(orderDf$id)){
    
    cur<-orderDf[orderDf$subID==i & orderDf$id==j, c("order","T.Sim")]
  
    if(all(cur["order"]==0) | all(cur["T.Sim"]==0)){
    orderDf$PCAid[orderDf$subID==i & orderDf$id==j & !is.na(orderDf$order) & !is.na(orderDf$T.Sim)] <- PCAid$x[,1]
    }else{
      PCAid<- prcomp(na.omit(cur),
             center = TRUE,
            scale. = TRUE)
    orderDf$PCAid[orderDf$subID==i & orderDf$id==j & !is.na(orderDf$order) & !is.na(orderDf$T.Sim)] <- PCAid$x[,1]
    }

  }
}
    
    cor(orderDf[c("PCAall","PCAsub","PCAid")], use="complete.obs")
```

```{r}
m<-lmer(selfRespZ ~ scale(order) + ( 1 | subID/id ) + ( 1 | traits), data=orderDf)
summary(m)

m<-lmer(selfRespZ ~ scale(T.Sim) + ( 1 | subID/id ) + ( 1 | traits), data=orderDf)
summary(m)

m<-lmer(selfRespZ ~ PCAallZ + ( 1 | subID/id ) + ( 1 | traits), data=orderDf)
summary(m)

m<-lmer(scale(selfResp) ~ scale(PCAsub) + ( 1 | subID/id ) + ( 1 | traits), data=orderDf)
summary(m)

m<-lmer(scale(selfResp) ~ scale(PCAid) + ( 1 | subID/id ) + ( 1 | traits), data=orderDf)
summary(m)
```






